#!/bin/bash
# SCRIPT: pushdevconf
# PURPOSE: PUSH CURRENT CONFIGURATION FILES TO REMOTE REPOSITORY IN GITHUB
# AUTHOR: EDUARDO ZUCARATO
# DATE: 2019/NOV/17
echo
echo "We are going to push current configuration files to DevConf remote repo"

# These are the config files to push to remote repo 
files=( .gitconfig
	.bash_profile 
	.bash_aliases
	.vimrc )

# Exhibits file list
echo
echo The files are:
for i in ${files[@]}; do echo $i; done

# Reads answer and procceeds 
read -t 3 -n 1 -p "Are you sure(y/n)? " answer
if [ $? != 0 ]; then
    # No input
    echo
    echo "Can't wait for ever!"
else
    if [ "$answer" != "${answer#[Yy]}" ] ;then
    	echo
	echo User says YES!	
	echo
	cd ~/DevConf	
	git checkout master

	echo
	echo Deleting previous existing files in DevConf directory
	for file in ${files[@]}; do rm -v $HOME/DevConf/$file; done

	echo
	echo Copying files from home to ~/DevConf
	for file in ${files[@]}; do 
	    cp -vf $HOME/$file $HOME/DevConf;
	    done
	
	echo
	echo Adding new files
	git add ${files[@]}

	echo
	echo Commiting updates
	git commit -am "Update by $0 script"

	echo
	echo Pushing into remote repository...
	git push origin master

    else
	# User says NO...
	echo
    	echo No
    fi 
fi
